nodeLinker: node-modules

npmRegistries:
    "https://npm.pkg.github.com":
        npmAlwaysAuth: true
    "https://registry.npmjs.org":
        npmAlwaysAuth: true

#npmScopes:
#    "qinetik":
#        npmAlwaysAuth: true
#        npmAuthToken: "${GPR_API_KEY}"
#        npmRegistryServer: "https://npm.pkg.github.com"
#        npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
    "qinetik":
        npmAlwaysAuth: true
        npmAuthToken: "${NPM_PUB_TOKEN}"
        npmRegistryServer: "https://registry.npmjs.org"
        npmPublishRegistry: "https://registry.npmjs.org"

npmPublishRegistry: "https://registry.npmjs.org"